/** Original Goa-flavoured sentence bank. Tier 1: 4–6 words, Tier 2: 6–9, Tier 3: 8–13. */

export const TIER1: string[] = [
  'The sea is calling.',
  'Warm sand under my feet.',
  "Let's race to the shack.",
  'Palm trees wave hello.',
  'Catch the morning wind.',
  'The tide is rising fast.',
  'Fresh coconut water, please.',
  'Seagulls follow our boat.',
  'The sun paints the waves.',
  'Ride the wake to victory.',
  'Golden light on Baga beach.',
  'My voice is the engine.',
  'Fishing boats leave at dawn.',
  'Hold steady through the spray.',
  'The river meets the sea.',
  'Cashews taste better by the shore.',
  'Bright shutters, blue skies.',
  'Faster than the morning ferry.',
  'Salt air fills the sails.',
  'Every word pushes us forward.',
  'The lighthouse blinks hello.',
  'Splash through the turquoise water.',
  'Goa never sleeps tonight.',
  'Steer clear of the buoys.',
  'The breeze smells like mango.',
  'Feel the rhythm of the waves.',
  'A sailboat drifts past slowly.',
  'Speak up and speed up.',
  'Crabs dance on the sand.',
  'The beach shack plays music.',
  'Waves crash on the rocks.',
  'Chase the sunset home.',
  'Hot pao from the bakery.',
  'The water sparkles like glitter.',
  'Nobody beats a steady voice.',
  'Follow the trail of cashews.',
];

export const TIER2: string[] = [
  'The fishing boats glide past the old fort.',
  'Fresh bread arrives at the market every morning.',
  'A yellow balcony hangs above the quiet canal.',
  'Bright umbrellas bloom along the golden coast.',
  'The ferry horn echoes across the wide river.',
  'Grandmother bakes bebinca in seven careful layers.',
  'Colourful houses lean over the narrow lanes.',
  'We race past the shacks before lunch time.',
  'The old church bells ring across the water.',
  'Spice sellers shout their prices at Mapusa market.',
  'Chapora fort watches over the river mouth.',
  'Strings of lights glow above the flea market.',
  'A scooter zooms along the coconut lined road.',
  'Monsoon clouds gather over the green hills.',
  'Every captain dreams of winning this regatta.',
  'The wind carries music from the beach party.',
  'Painted fishing canoes rest on the white sand.',
  'Our boat cuts through the waves like butter.',
  'The market smells of cinnamon and fresh fish.',
  'Kingfishers dive into the shimmering mangrove water.',
  'Sunset turns the whole sky pink and orange.',
  'Hold the line and keep your rhythm steady.',
  'Dolphins sometimes jump beside the morning boats.',
  'The baker rings his bicycle bell at dawn.',
  'Red tiled roofs shine after the summer rain.',
  'Lanterns float slowly down the dark river.',
  'A gentle breeze cools the busy fish market.',
  'Rival captains wave as we zoom past them.',
  'Fontainhas houses are painted fresh every year.',
  'The bridge lights reflect on the calm water.',
  'Speak clearly and the boat will fly.',
  'Mango trees shade the sleepy village square.',
  'Our wake leaves a white ribbon behind us.',
  'Friends cheer loudly from the wooden jetty.',
  'Fireworks bloom over the river at midnight.',
  'The coconut seller climbs the tallest palm tree.',
];

export const TIER3: string[] = [
  'Seagulls circle the ferry as the evening bells ring across the river.',
  'Please pass the bebinca before the monsoon washes the road away.',
  'Colourful houses lean over narrow lanes that smell of fresh pao.',
  'The fishermen pull their nets while the sun climbs over the hills.',
  'Strings of lanterns sway above the boats during the festival night.',
  'A steady voice and a brave heart will win this coastal race.',
  'Old Portuguese balconies glow yellow and green in the afternoon light.',
  'The market at Mapusa opens early with baskets of spices and fruit.',
  'Our boat flies past the fort as the crowd cheers from the cliffs.',
  'Thunder rolls across the Mandovi while we race toward the bridge.',
  'Every clean sentence pushes our little boat closer to the finish line.',
  'Waves of music drift from the shacks as the sun slowly sets.',
  'The night regatta lights up the river with a thousand tiny stars.',
  'Grandfather says the river remembers every captain who raced on it.',
  'A warm breeze carries the smell of cashew trees across the water.',
  'Bright red roofs and white churches line the banks of the river.',
  'We dodge the floating logs and chase the leader into the bend.',
  'The ferry captain waves his cap as our boats zoom past him.',
  'Fireworks explode in magenta and gold above the cheering harbour crowd.',
  'Hold your rhythm steady and let the words carry you home.',
  'Fishing canoes painted with bright eyes guard the quiet morning shore.',
  'Under the golden sun the whole coast feels like one big celebration.',
  'Monsoon rain drums on the tin roofs while the river swells higher.',
  'The bakery van honks twice as it rolls through the sleepy village.',
  'Our rivals are fast but nobody speaks with more heart than us.',
  'Late at night the bridge lights shimmer on the dark water below.',
  'A gentle susegad afternoon turns into the fastest race of the year.',
  'The lighthouse on the cliff guides every boat safely back to shore.',
];

export const TONGUE_TWISTERS: string[] = [
  'Six silver sailboats skim the shining sea.',
  'Cashew crunch and coconut crush on the Candolim coast.',
  'Fresh fried fish fills four fishing families.',
  'Brave boats bob beside the busy Baga beach.',
  'Pink painted pillars prop up the pretty porch.',
];

export const BONUS_PHRASES: string[] = [
  'Full steam ahead', 'Catch the tide', 'Susegad speed', 'Ride the wave', 'Feel the breeze',
  'Sunset sprint', 'Faster than feni', 'Cashew power', 'Wake up the sea', 'Goa is calling',
  'Hold the line', 'Chase the sun', 'Light the lanterns', 'Splash and dash', 'Coconut rocket',
  'Make some waves', 'Fly past the fort', 'Spice up the race', 'Bring the thunder', 'Bells of victory',
];

export const GOA_DICTIONARY = [
  'Panjim', 'Mapusa', 'Margao', 'Vasco da Gama', 'Mandovi', 'Zuari', 'Chapora', 'Anjuna', 'Vagator',
  'Calangute', 'Candolim', 'Baga', 'Palolem', 'Agonda', 'Aguada', 'Miramar', 'Dudhsagar', 'Fontainhas',
  'Divar', 'Cabo de Rama', 'Bebinca', 'Xacuti', 'Sorpotel', 'Vindaloo', 'Pao', 'Poi', 'Caju', 'Feni',
  'Susegad', 'Shigmo', 'Konkani', 'Goenkar', 'Azulejo', 'Dona Paula', 'Old Goa', 'Reis Magos', 'Arambol',
  'Morjim', 'Balcao',
];

export const HARD_WORDS = new Set(['bebinca', 'xacuti', 'susegad', 'fontainhas', 'mandovi', 'chapora', 'mapusa',
  'candolim', 'kingfishers', 'portuguese', 'regatta', 'cinnamon', 'mangrove', 'lanterns', 'shimmering']);

export const GOA_FACTS: string[] = [
  'SUSEGAD (adj.) — the Goan art of relaxed contentment. Not today, captain.',
  'Fontainhas homes are traditionally repainted every year after the monsoon.',
  'Bebinca is a layered Goan dessert — some bakers stack up to sixteen layers.',
  'Goa’s rivers — the Mandovi and the Zuari — meet the Arabian Sea near Panjim.',
  'Ro-Ro ferries have carried people and scooters across Goan rivers for decades.',
  'Cashew trees arrived in Goa centuries ago and never left.',
  'Konkani is the official language of Goa. “Goem” (गोंय) is Goa in Konkani.',
  'Painted eyes on fishing canoes are said to help the boat find its way home.',
  'Chapora Fort overlooks the Chapora river mouth near Vagator.',
  'Shigmo is Goa’s spring festival of colour, music and floats.',
];
